services:
  flask_app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
#    networks:
#      - bridge
#
#networks:
#  bridge:
#    external: true