version: '3.8'
services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b :5000 app:app
    volumes:
      - .:/usr/src/app
#    networks:
#      - backend
    env_file:
      - .env
#networks:
#  backend:
#    driver: bridge
